import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GeneralLayout from "./GeneralLayout";
import { AuthProvider } from "@/app/shared/contexts/AuthContext"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FoodScore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <AuthProvider> 
          <GeneralLayout>{children}</GeneralLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
